version: '3'

services:
  # nombre del servio
  dbmysql: 
    # imagen a utilizar
    image: mysql:8.0.33

    # nombre del contenedor
    container_name: db-mysql

    # variables de entorno
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test

    # mapeo de puertos
    ports:
      - 3306:3306

    volumes:
      - ./dbdata/mysql:/var/lib/mysql

  dbmongo:
    image: mongo:6.0
    restart: always
    container_name: db-mongo
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: micontrasenia
      MONGO_INITDB_DATABASE: mibasededatos
    
    volumes:
      - ./mongo-volume:/data/db
    
    ports:
      - 27017:27017

  servidor:
    # nombre del contendor
    container_name: server-express

    # imagen a utilizar
    build:
      # carpeta donde se encuentra el codigo
      context: ./server

      # ubica el dockerfile
      dockerfile: Dockerfile

    # variables de entorno
    environment:
      PORT: 3000
      DATABASE_HOST: dbmysql
      DATABASE_USER: root
      DATABASE_PASSWORD: secret
      DATABASE_NAME: test

      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: micontrasenia
      ME_CONFIG_MONGODB_DATABASE: mibasededatos


    # si falla intenta reiniciarse
    restart: always

    # dependencias del contenedor
    depends_on:
      - dbmysql
      - dbmongo

    # mapeo de puertos
    ports:
      - 3000:3000

    volumes:
      - ./server:/server